SELECT INTITULE,CURRENT_PRICE,DESCRIPTION, URL_PHOTO, PRODUCT.PRODUCT_ID,
COUNT(OFFERS.PRODUCT_ID) AS Nb_offres FROM PRODUCT LEFT JOIN OFFERS ON PRODUCT.PRODUCT_ID = OFFERS.PRODUCT_ID
WHERE CATEGORY_NOM='novels' GROUP BY PRODUCT.PRODUCT_ID, INTITULE, CURRENT_PRICE,DESCRIPTION, URL_PHOTO ORDER BY Nb_offres DESC, UPPER(INTITULE);
